apiVersion: v1
kind: ConfigMap
metadata:
  name: egi-config
  namespace: egi-inventario
data:
  # MongoDB interno al cluster
  MONGO_URI: "mongodb://egi-mongodb:27017/inventario_egi"
  
  # SQL Server externo (VM)
  DB_URL: "jdbc:sqlserver://192.168.10.20:1433;databaseName=inventario_egi;encrypt=false;trustServerCertificate=true"
  DB_USER: "sa"
  
  # Configuración Frontend y CORS
  # Se contempla el puerto 30443 del Ingress
  CORS_ALLOWED_ORIGINS: "https://egi-inventario.local:30443,http://egi-inventario.local:30443"
  VITE_API_URL: "https://egi-inventario.local:30443/api"
  VITE_USE_MOCK: "false"
