apiVersion: v1
kind: Secret
metadata:
  name: egi-secret
  namespace: egi-inventario
type: Opaque
stringData:
  # Se utiliza stringData para no tener que codificar manualmente en Base64 aquí
  DB_PASSWORD: "EGI_Password123!"
