apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: egi-ingress
  namespace: egi-inventario
spec:
  ingressClassName: nginx
  rules:
  - host: inventario.itu.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: egi-backend
            port:
              number: 8080
