apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventario-web
  namespace: inventario-seguro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventario-web
  template:
    metadata:
      labels:
        app: inventario-web
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
      - name: inventario-web
        image: ghcr.io/juanmahumeniuk/inventario-web:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: sql-secret
        - secretRef:
            name: ldap-secret
        - secretRef:
            name: mongo-secret
        - secretRef:
            name: jwt-secret
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
