apiVersion: apps/v1
kind: Deployment
metadata:
  name: egi-frontend
  namespace: egi-inventario
spec:
  replicas: 1
  selector:
    matchLabels:
      app: egi-frontend
  template:
    metadata:
      labels:
        app: egi-frontend
    spec:
      containers:
      - name: frontend
        # Se asume que la imagen se cargará a minikube: minikube image load egi-frontend:latest
        image: egi-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: egi-frontend
  namespace: egi-inventario
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: egi-frontend
