flowchart TB
    U([Usuario Institucional])

    subgraph VM1["VM 1: Firewall (pfSense)"]
        FW["Firewall Perimetral<br/>(Simulación DMZ)"]
    end

    subgraph VM2["VM 2: Windows Server"]
        AD["Active Directory / LDAP<br/>(Puertos :389 / :636)"]
        DNS["DNS Server<br/>(Resolución interna)"]
    end

    subgraph VM3["VM 3: SQL Server"]
        SQL["SQL Server<br/>(Puerto :1433)"]
    end

    subgraph VM4["VM 4: Kubernetes (Minikube + Calico)"]
        IC["Ingress Controller<br/>(inventario.itu.local)"]
        FE["inventario-web<br/>(Spring Boot + React)"]
        MONGO["inventario-db<br/>(MongoDB :27017)"]
        PV2["PVC mongodb-data"]
    end

    U -->|HTTPS| FW
    FW -->|HTTPS| IC
    IC --> FE
    FE -->|LDAP/LDAPS| AD
    FE -->|DNS query| DNS
    FE -->|JDBC :1433| SQL
    FE -->|Mongo Wire :27017| MONGO
    MONGO -.->|persistencia| PV2

    classDef edge fill:#1f2937,stroke:#374151,color:#fff
    classDef app fill:#0f766e,stroke:#0d9488,color:#fff
    classDef db fill:#7c2d12,stroke:#9a3412,color:#fff
    classDef sec fill:#1e3a8a,stroke:#1d4ed8,color:#fff
    classDef vol fill:#374151,stroke:#4b5563,color:#fff

    class FW edge
    class IC,FE app
    class SQL,MONGO db
    class AD,DNS sec
    class PV2 vol
