flowchart TB
    USER(("Usuario<br/>institucional"))

    subgraph PERIMETRO["Perímetro · Zero-Trust"]
        FW["Firewall / DMZ<br/>GUFW · pfSense"]
    end

    subgraph CLUSTER["Clúster Kubernetes · Minikube (CNI Calico)"]
        direction TB
        ING["Ingress Controller"]

        subgraph NS["Namespace · inventario-seguro"]
            direction TB
            WEB["inventario-web<br/><i>Spring Boot · Frontend+API</i>"]

            subgraph DATA["Capa de datos"]
                direction LR
                SQL[("ubicacion-db<br/><i>SQL Server</i><br/>persona · maquina · persona_maquina")]
                MONGO[("inventario-db<br/><i>MongoDB</i><br/>colección maquina (hardware)")]
            end

            LDAP["ldap-service<br/><i>Active Directory / LDAP</i>"]
        end

        subgraph PV["Persistencia (PersistentVolumes)"]
            direction LR
            SQLPV[["PVC sqlserver-data"]]
            MONGOPV[["PVC mongodb-data"]]
            LDAPPV[["PVC ldap-data"]]
        end
    end

    USER -->|HTTPS| FW
    FW -->|HTTP| ING
    ING --> WEB

    WEB -->|JDBC :1433| SQL
    WEB -->|Mongo Wire :27017| MONGO
    WEB -->|LDAP/LDAPS :389/636| LDAP

    SQL -.-> SQLPV
    MONGO -.-> MONGOPV
    LDAP -.-> LDAPPV

    classDef edge fill:#1f2937,stroke:#374151,color:#fff;
    classDef app fill:#0f766e,stroke:#0d9488,color:#fff;
    classDef db fill:#7c2d12,stroke:#9a3412,color:#fff;
    classDef sec fill:#1e3a8a,stroke:#1d4ed8,color:#fff;
    classDef vol fill:#374151,stroke:#4b5563,color:#fff;

    class FW edge;
    class WEB,ING app;
    class SQL,MONGO db;
    class LDAP sec;
    class SQLPV,MONGOPV,LDAPPV vol;
